# Generated by Django 3.0.7 on 2020-12-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0017_auto_20201212_0059"),
        ("reeltalk", "0022_auto_20201212_1744"),
    ]

    operations = []
