# Generated by Django 3.0.7 on 2020-12-17 03:17

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0025_auto_20201217_0046"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="content_warning",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=500, null=True
            ),
        ),
    ]
