# Generated by Django 3.0.7 on 2020-12-24 19:39

import reeltalk.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0029_auto_20201221_2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="localname",
            field=models.CharField(
                max_length=255,
                null=True,
                unique=True,
                validators=[reeltalk.models.fields.validate_localname],
            ),
        ),
    ]
