# Generated by Django 3.0.7 on 2021-01-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0038_auto_20210119_1534"),
        ("reeltalk", "0015_auto_20201128_0734"),
    ]

    operations = []
