# Generated by Django 3.0.7 on 2021-01-22 00:57

import reeltalk.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0039_merge_20210120_0753"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressupdate",
            name="progress",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="progressupdate",
            name="readthrough",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reeltalk.ReadThrough"
            ),
        ),
        migrations.AlterField(
            model_name="progressupdate",
            name="remote_id",
            field=reeltalk.models.fields.RemoteIdField(
                max_length=255,
                null=True,
                validators=[reeltalk.models.fields.validate_remote_id],
            ),
        ),
        migrations.AlterField(
            model_name="readthrough",
            name="progress",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
