# Generated by Django 3.0.7 on 2021-01-31 16:14

import reeltalk.models.activitypub_mixin
import reeltalk.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0040_auto_20210122_0057"),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "remote_id",
                    reeltalk.models.fields.RemoteIdField(
                        max_length=255,
                        null=True,
                        validators=[reeltalk.models.fields.validate_remote_id],
                    ),
                ),
                ("name", reeltalk.models.fields.CharField(max_length=100)),
                (
                    "description",
                    reeltalk.models.fields.TextField(blank=True, null=True),
                ),
                (
                    "privacy",
                    reeltalk.models.fields.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("followers", "Followers"),
                            ("direct", "Direct"),
                        ],
                        default="public",
                        max_length=255,
                    ),
                ),
                (
                    "curation",
                    reeltalk.models.fields.CharField(
                        choices=[
                            ("closed", "Closed"),
                            ("open", "Open"),
                            ("curated", "Curated"),
                        ],
                        default="closed",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                reeltalk.models.activitypub_mixin.OrderedCollectionMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "remote_id",
                    reeltalk.models.fields.RemoteIdField(
                        max_length=255,
                        null=True,
                        validators=[reeltalk.models.fields.validate_remote_id],
                    ),
                ),
                ("notes", reeltalk.models.fields.TextField(blank=True, null=True)),
                ("approved", models.BooleanField(default=True)),
                ("order", reeltalk.models.fields.IntegerField(blank=True, null=True)),
                (
                    "added_by",
                    reeltalk.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "book",
                    reeltalk.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reeltalk.Edition",
                    ),
                ),
                (
                    "book_list",
                    reeltalk.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reeltalk.List"
                    ),
                ),
                (
                    "endorsement",
                    models.ManyToManyField(
                        related_name="endorsers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-created_date",),
                "unique_together": {("book", "book_list")},
            },
            bases=(reeltalk.models.activitypub_mixin.ActivitypubMixin, models.Model),
        ),
        migrations.AddField(
            model_name="list",
            name="books",
            field=models.ManyToManyField(
                through="reeltalk.ListItem", to="reeltalk.Edition"
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="user",
            field=reeltalk.models.fields.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
