# Generated by Django 3.1.6 on 2021-03-21 21:44

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0056_auto_20210321_0303"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discoverable",
            field=reeltalk.models.fields.BooleanField(default=False),
        ),
    ]
