# Generated by Django 3.1.6 on 2021-04-07 15:45

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0061_auto_20210402_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="series",
            field=reeltalk.models.fields.TextField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="subtitle",
            field=reeltalk.models.fields.TextField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=reeltalk.models.fields.TextField(max_length=255),
        ),
    ]
