# Generated by Django 3.1.6 on 2021-04-07 00:45

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0062_auto_20210406_1731"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="bnf_id",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="gutenberg_id",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="inventaire_id",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="isni",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="viaf_id",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="bnf_id",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="inventaire_id",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
