# Generated by Django 3.2.4 on 2021-06-23 21:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0076_preview_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="author",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="reeltalk_au_search__b050a8_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="reeltalk_bo_search__51beb3_gin"
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION book_trigger() RETURNS trigger AS $$
                begin
                    new.search_vector :=
                        coalesce(
                            NULLIF(setweight(to_tsvector('english', coalesce(new.title, '')), 'A'), ''),
                            setweight(to_tsvector('simple', coalesce(new.title, '')), 'A')
                        ) ||
                        setweight(to_tsvector('english', coalesce(new.subtitle, '')), 'B') ||
                        (SELECT setweight(to_tsvector('simple', coalesce(array_to_string(array_agg(reeltalk_author.name), ' '), '')), 'C')
                            FROM reeltalk_book
                            LEFT OUTER JOIN reeltalk_book_authors
                            ON reeltalk_book.id = reeltalk_book_authors.book_id
                            LEFT OUTER JOIN reeltalk_author
                            ON reeltalk_book_authors.author_id = reeltalk_author.id
                            WHERE reeltalk_book.id = new.id
                        ) ||
                        setweight(to_tsvector('english', coalesce(new.series, '')), 'D');
                    return new;
                end
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER search_vector_trigger
                BEFORE INSERT OR UPDATE OF title, subtitle, series, search_vector
                ON reeltalk_book
                FOR EACH ROW EXECUTE FUNCTION book_trigger();

                UPDATE reeltalk_book SET search_vector = NULL;
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS search_vector_trigger
                ON reeltalk_book;
                DROP FUNCTION IF EXISTS book_trigger;
            """,
        ),
        # when an author is edited
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION author_trigger() RETURNS trigger AS $$
                begin
                    WITH book AS (
                        SELECT reeltalk_book.id as row_id
                        FROM reeltalk_author
                        LEFT OUTER JOIN reeltalk_book_authors
                        ON reeltalk_book_authors.id = new.id
                        LEFT OUTER JOIN reeltalk_book
                        ON reeltalk_book.id = reeltalk_book_authors.book_id
                    )
                    UPDATE reeltalk_book SET search_vector = ''
                    FROM book
                    WHERE id = book.row_id;
                    return new;
                end
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER author_search_vector_trigger
                AFTER UPDATE OF name
                ON reeltalk_author
                FOR EACH ROW EXECUTE FUNCTION author_trigger();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS author_search_vector_trigger
                ON reeltalk_author;
                DROP FUNCTION IF EXISTS author_trigger;
            """,
        ),
        # when an author is added to or removed from a book
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION book_authors_trigger() RETURNS trigger AS $$
                begin
                    UPDATE reeltalk_book SET search_vector = ''
                    WHERE id = coalesce(new.book_id, old.book_id);
                    return new;
                end
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER book_authors_search_vector_trigger
                AFTER INSERT OR DELETE
                ON reeltalk_book_authors
                FOR EACH ROW EXECUTE FUNCTION book_authors_trigger();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS book_authors_search_vector_trigger
                ON reeltalk_book_authors;
                DROP FUNCTION IF EXISTS book_authors_trigger;
            """,
        ),
    ]
