# Generated by Django 3.2.4 on 2021-09-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0095_auto_20210911_2053"),
        ("reeltalk", "0095_merge_20210911_2143"),
    ]

    operations = []
