# Generated by Django 3.2 on 2021-05-21 00:17

from django.db import migrations
import reeltalk


# Inlined from connectors/format_mappings.py + abstract_connector.infer_physical_format,
# which no longer exist.
format_mappings = {
    "paperback": "Paperback",
    "soft": "Paperback",
    "pamphlet": "Paperback",
    "peperback": "Paperback",
    "tapa blanda": "Paperback",
    "turtleback": "Paperback",
    "pocket": "Paperback",
    "spiral": "Paperback",
    "ring": "Paperback",
    "平装": "Paperback",
    "简装": "Paperback",
    "hardcover": "Hardcover",
    "hardcocer": "Hardcover",
    "hardover": "Hardcover",
    "hardback": "Hardcover",
    "library": "Hardcover",
    "tapa dura": "Hardcover",
    "leather": "Hardcover",
    "clothbound": "Hardcover",
    "精装": "Hardcover",
    "ebook": "EBook",
    "e-book": "EBook",
    "digital": "EBook",
    "computer file": "EBook",
    "epub": "EBook",
    "online": "EBook",
    "pdf": "EBook",
    "elektronische": "EBook",
    "electronic": "EBook",
    "audiobook": "AudiobookFormat",
    "audio": "AudiobookFormat",
    "cd": "AudiobookFormat",
    "dvd": "AudiobookFormat",
    "mp3": "AudiobookFormat",
    "cassette": "AudiobookFormat",
    "kindle": "AudiobookFormat",
    "talking": "AudiobookFormat",
    "sound": "AudiobookFormat",
    "comic": "GraphicNovel",
    "graphic": "GraphicNovel",
}


def infer_physical_format(format_text):
    """try to figure out what the standardized format is from the free value"""
    format_text = format_text.lower()
    if format_text in format_mappings:
        # try a direct match
        return format_mappings[format_text]
    # failing that, try substring
    matches = [v for k, v in format_mappings.items() if k in format_text]
    if not matches:
        return None
    return matches[0]


def infer_format(app_registry, schema_editor):
    """set the new physical format field based on existing format data"""
    db_alias = schema_editor.connection.alias

    editions = (
        app_registry.get_model("reeltalk", "Edition")
        .objects.using(db_alias)
        .filter(physical_format_detail__isnull=False)
    )
    for edition in editions:
        free_format = edition.physical_format_detail.lower()
        edition.physical_format = infer_physical_format(free_format)
        edition.save()


def reverse(app_registry, schema_editor):
    """doesn't need to do anything"""


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0100_shelf_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edition",
            old_name="physical_format",
            new_name="physical_format_detail",
        ),
        migrations.AddField(
            model_name="edition",
            name="physical_format",
            field=reeltalk.models.fields.CharField(
                blank=True,
                choices=[
                    ("AudiobookFormat", "Audiobook"),
                    ("EBook", "eBook"),
                    ("GraphicNovel", "Graphic novel"),
                    ("Hardcover", "Hardcover"),
                    ("Paperback", "Paperback"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(infer_format, reverse),
    ]
