# Generated by Django 3.2.5 on 2021-10-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0107_auto_20211016_0639"),
        ("reeltalk", "0110_auto_20211015_1734"),
    ]

    operations = []
