# Generated by Django 3.2.5 on 2022-01-04 18:59

import reeltalk.models.user
from django.db import migrations, models
from django.utils import timezone


def get_current_year():
    """inlined from the removed reeltalk.models.annual_goal module"""
    return timezone.now().year


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0121_user_summary_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualgoal",
            name="year",
            field=models.IntegerField(default=get_current_year),
        ),
    ]
