# Generated by Django 3.2.5 on 2022-01-04 18:59

import reeltalk.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0121_user_summary_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualgoal",
            name="year",
            field=models.IntegerField(
                default=reeltalk.models.annual_goal.get_current_year
            ),
        ),
    ]
