# Generated by Django 3.2.10 on 2022-01-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0126_auto_20220112_2315"),
        ("reeltalk", "0127_auto_20220110_2211"),
    ]

    operations = []
