# Generated by Django 3.2.10 on 2022-01-24 20:01

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0129_auto_20220117_1716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="notes",
            field=reeltalk.models.fields.TextField(
                blank=True, max_length=300, null=True
            ),
        ),
    ]
