# Generated by Django 3.2.12 on 2022-02-17 16:24

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0134_announcement_display_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="viaf_id",
            new_name="viaf",
        ),
        migrations.RemoveField(
            model_name="edition",
            name="asin",
        ),
        migrations.AddField(
            model_name="author",
            name="asin",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="wikidata",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="asin",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="viaf",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="wikidata",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
