# Generated by Django 3.2.12 on 2022-02-28 19:44

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0141_alter_report_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hide_follows",
            field=reeltalk.models.fields.BooleanField(default=False),
        ),
    ]
