# Generated by Django 3.2.16 on 2022-12-06 09:02

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0168_auto_20221205_1701"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="isfdb",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="isfdb",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
