# Generated by Django 3.2.23 on 2024-01-28 02:49

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
from django.core.files.storage import storages


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0192_sitesettings_user_exports_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="reeltalkexportjob",
            name="export_json",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="reeltalkexportjob",
            name="json_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reeltalkexportjob",
            name="export_data",
            field=models.FileField(
                null=True,
                storage=storages["exports"],
                upload_to="",
            ),
        ),
        migrations.CreateModel(
            name="AddFileToTar",
            fields=[
                (
                    "childjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reeltalk.childjob",
                    ),
                ),
                (
                    "parent_export_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_edition_export_jobs",
                        to="reeltalk.reeltalkexportjob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("reeltalk.childjob",),
        ),
        migrations.CreateModel(
            name="AddBookToUserExportJob",
            fields=[
                (
                    "childjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reeltalk.childjob",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reeltalk.edition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("reeltalk.childjob",),
        ),
    ]
