# Generated by Django 3.2.23 on 2024-02-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0192_rename_version_sitesettings_available_version"),
        ("reeltalk", "0193_merge_20240203_1539"),
    ]

    operations = []
