# Generated by Django 3.2.23 on 2024-03-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0191_migrate_search_vec_triggers_to_pgtriggers"),
        ("reeltalk", "0195_alter_user_preferred_language"),
    ]

    operations = []
