# Generated by Django 3.2.25 on 2024-03-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0198_alter_reeltalkexportjob_export_data"),
        ("reeltalk", "0198_book_search_vector_author_aliases"),
    ]

    operations = []
