# Generated by Django 3.2.25 on 2024-04-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0202_user_reeltalk_us_usernam_b2546d_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "local"], name="reeltalk_us_is_acti_972dc4_idx"
            ),
        ),
    ]
