# Generated by Django 3.2.25 on 2024-04-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0197_mergedauthor_mergedbook"),
        ("reeltalk", "0203_user_reeltalk_us_is_acti_972dc4_idx"),
    ]

    operations = []
