# Generated by Django 4.2.11 on 2024-07-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0207_merge_20240629_0626"),
        ("reeltalk", "0207_sqlparse_update"),
    ]

    operations = []
