# Generated by Django 4.2.17 on 2025-02-08 16:14

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0210_alter_connector_connector_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="finna_key",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="finna_key",
            field=reeltalk.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
