# Generated by Django 4.2.20 on 2025-05-02 18:17

import reeltalk.models.fields
from django.db import migrations


def _no_op_validator(value):
    """Placeholder for the ISBN validators that lived in models/book.py, which no longer exists."""


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0213_alter_user_preferred_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="isbn_10",
            field=reeltalk.models.fields.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[_no_op_validator],
            ),
        ),
        migrations.AlterField(
            model_name="edition",
            name="isbn_13",
            field=reeltalk.models.fields.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[_no_op_validator],
            ),
        ),
    ]
