# Generated by Django 4.2.22 on 2025-07-27 06:03

import reeltalk.models.reeltalk_export_job
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0214_alter_edition_isbn_10_alter_edition_isbn_13"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserRelationshipImport",
            new_name="UserImportRelationship",
        ),
        migrations.AlterField(
            model_name="reeltalkimportjob",
            name="archive_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=reeltalk.models.reeltalk_export_job.select_exports_storage,
                upload_to="",
            ),
        ),
    ]
