# Generated by Django 5.2.3 on 2025-09-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0217_merge_20250816_0749"),
        ("reeltalk", "0217_usersession"),
    ]

    operations = []
