# Generated by Django 5.2.3 on 2025-11-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reeltalk", "0219_findmissingcoversjob"),
        ("reeltalk", "0221_user_force_password_reset"),
    ]

    operations = []
