# Generated by Django 5.2.9 on 2026-01-22 18:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0224_book_reeltalk_bo_remote__43009f_bloom_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='reeltalk_bo_remote__43009f_bloom',
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.BloomIndex(fields=['origin_id', 'remote_id', 'openlibrary_key', 'finna_key', 'inventaire_id', 'librarything_key', 'goodreads_key', 'bnf_id', 'viaf', 'wikidata', 'asin', 'aasin', 'isfdb'], name='reeltalk_bo_origin__a05fb1_bloom'),
        ),
    ]
