# Generated by Django 5.2.9 on 2026-01-24 17:29

import reeltalk.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0225_remove_book_reeltalk_bo_remote__43009f_bloom_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='reeltalk_bo_origin__a05fb1_bloom',
        ),
        migrations.AddField(
            model_name='author',
            name='libris_key',
            field=reeltalk.models.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='libris_key',
            field=reeltalk.models.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='connector_file',
            field=models.CharField(choices=[('openlibrary', 'Openlibrary'), ('inventaire', 'Inventaire'), ('reeltalk_connector', 'Reeltalk Connector'), ('finna', 'Finna'), ('libris', 'Libris')], max_length=255),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.BloomIndex(fields=['origin_id', 'remote_id', 'openlibrary_key', 'finna_key', 'libris_key', 'inventaire_id', 'librarything_key', 'goodreads_key', 'bnf_id', 'viaf', 'wikidata', 'asin', 'aasin', 'isfdb'], name='reeltalk_bo_origin__d045df_bloom'),
        ),
    ]
