# Generated by Django 5.2.9 on 2026-01-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0226_remove_book_reeltalk_bo_origin__a05fb1_bloom_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['parent_work', '-edition_rank'], name='reeltalk_ed_parent__c4f87c_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['privacy', '-updated_date'], name='reeltalk_li_privacy_a38257_idx'),
        ),
    ]
