# Generated by Django 5.2.9 on 2026-02-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0211_remove_report_status_alter_report_statuses'),
        ('reeltalk', '0227_edition_reeltalk_ed_parent__c4f87c_idx_and_more'),
    ]

    operations = [
    ]
