# Generated by Django 5.2.9 on 2026-05-16 10:45

import reeltalk.models.activitypub_mixin
import reeltalk.models.fields
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0228_remove_user_reeltalk_us_is_acti_972dc4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('remote_id', reeltalk.models.fields.RemoteIdField(max_length=255, null=True, validators=[reeltalk.models.fields.validate_remote_id])),
                ('origin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('openlibrary_key', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('finna_key', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('libris_key', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('inventaire_id', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('librarything_key', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('goodreads_key', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('bnf_id', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('viaf', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('wikidata', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('asin', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('aasin', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('isfdb', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('name', reeltalk.models.fields.TextField(max_length=255)),
                ('alternative_names', reeltalk.models.fields.ArrayField(base_field=reeltalk.models.fields.CharField(max_length=255), blank=True, default=list, size=None)),
                ('last_edited_by', reeltalk.models.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user', reeltalk.models.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(reeltalk.models.activitypub_mixin.OrderedCollectionMixin, reeltalk.models.activitypub_mixin.ObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MergedSeries',
            fields=[
                ('deleted_id', models.IntegerField(primary_key=True, serialize=False)),
                ('merged_into', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absorbed', to='reeltalk.series')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('remote_id', reeltalk.models.fields.RemoteIdField(max_length=255, null=True, validators=[reeltalk.models.fields.validate_remote_id])),
                ('series_number', reeltalk.models.fields.CharField(blank=True, max_length=255, null=True)),
                ('book', reeltalk.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriesbooks', to='reeltalk.book')),
                ('series', reeltalk.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriesbooks', to='reeltalk.series')),
                ('user', reeltalk.models.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['series_number'],
                'unique_together': {('book', 'series'), ('series', 'series_number')},
            },
            bases=(reeltalk.models.activitypub_mixin.CollectionItemMixin, models.Model),
        ),
    ]
