# Generated by Django 5.2.9 on 2026-04-25 07:17

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0228_remove_user_reeltalk_us_is_acti_972dc4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=reeltalk.models.fields.CharField(blank=True, max_length=255, null=True),
        ),
    ]
