# Generated by Django 5.2.14 on 2026-06-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0229_alter_report_statuses'),
        ('reeltalk', '0231_sitesettings_block_incoming_search_and_more'),
    ]

    operations = [
    ]
