# Generated by Django 5.2.14 on 2026-06-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0232_merge_20260606_0829'),
        ('reeltalk', '0234_listitem_raw_notes'),
    ]

    operations = [
    ]
