# Generated by Django 5.2.16 on 2026-08-23 04:45

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0243_auto_20260730_0926'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='author',
            name='update_search_vector_on_author_edit',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='author',
            name='reset_book_search_vector_on_author_edit',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='book',
            name='update_search_vector_on_book_edit',
        ),
        migrations.RenameIndex(
            model_name='author',
            new_name='reeltalk_au_search__801312_gin',
            old_name='reeltalk_au_search__b050a8_gin',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='reeltalk_bo_search__57a2c3_gin',
            old_name='reeltalk_bo_search__51beb3_gin',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='reeltalk_bo_origin__279b79_bloom',
            old_name='reeltalk_bo_origin__d045df_bloom',
        ),
        migrations.RenameIndex(
            model_name='edition',
            new_name='reeltalk_ed_isbn_10_a7ac17_bloom',
            old_name='reeltalk_ed_isbn_10_435a21_bloom',
        ),
        migrations.RenameIndex(
            model_name='edition',
            new_name='reeltalk_ed_parent__5f47c4_idx',
            old_name='reeltalk_ed_parent__c4f87c_idx',
        ),
        migrations.RenameIndex(
            model_name='keypair',
            new_name='reeltalk_ke_remote__9f32a2_idx',
            old_name='reeltalk_ke_remote__472927_idx',
        ),
        migrations.RenameIndex(
            model_name='list',
            new_name='reeltalk_li_privacy_456b0f_idx',
            old_name='reeltalk_li_privacy_a38257_idx',
        ),
        migrations.RenameIndex(
            model_name='status',
            new_name='reeltalk_st_remote__216787_idx',
            old_name='reeltalk_st_remote__06aeba_idx',
        ),
        migrations.RenameIndex(
            model_name='status',
            new_name='reeltalk_st_thread__953dab_idx',
            old_name='reeltalk_st_thread__cf064f_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='reeltalk_us_usernam_fc5f24_idx',
            old_name='reeltalk_us_usernam_b2546d_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='reeltalk_us_local_2bb35e_idx',
            old_name='reeltalk_us_local_40fe61_idx',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='author',
            trigger=pgtrigger.compiler.Trigger(name='update_search_vector_on_author_edit', sql=pgtrigger.compiler.UpsertTriggerSql(func="new.search_vector := setweight(to_tsvector('simple', new.name), 'A') || setweight(to_tsvector('simple', coalesce(array_to_string(new.aliases, ' '), '')), 'B');RETURN NEW;", hash='3342541842982f29d02fd7efa611ae26b4e18ea5', operation='INSERT OR UPDATE OF "name", "aliases", "search_vector"', pgid='pgtrigger_update_search_vector_on_author_edit_3b5fe', table='reeltalk_author', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='author',
            trigger=pgtrigger.compiler.Trigger(name='reset_book_search_vector_on_author_edit', sql=pgtrigger.compiler.UpsertTriggerSql(func="WITH updated_books AS (SELECT book_id FROM reeltalk_book_authors WHERE author_id = new.id) UPDATE reeltalk_book SET search_vector = '' FROM updated_books WHERE id = updated_books.book_id;RETURN NEW;", hash='bd141080f50d67648f69ed4765e748afb923d551', operation='UPDATE OF "name", "aliases"', pgid='pgtrigger_reset_book_search_vector_on_author_edit_d706a', table='reeltalk_author', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='book',
            trigger=pgtrigger.compiler.Trigger(name='update_search_vector_on_book_edit', sql=pgtrigger.compiler.UpsertTriggerSql(func="WITH author_names AS (SELECT array_to_string(reeltalk_author.name || reeltalk_author.aliases, ' ') AS name_and_aliases FROM reeltalk_author LEFT JOIN reeltalk_book_authors ON reeltalk_author.id = reeltalk_book_authors.author_id WHERE reeltalk_book_authors.book_id = new.id) SELECT setweight(coalesce(nullif(to_tsvector('english', new.title), ''), to_tsvector('simple', new.title)), 'A') || setweight(to_tsvector('english', coalesce(new.subtitle, '')), 'B') || (SELECT setweight(to_tsvector('simple', coalesce(array_to_string(array_agg(name_and_aliases), ' '), '')), 'C') FROM author_names) || setweight(to_tsvector('english', coalesce(new.series, '')), 'D') INTO new.search_vector;RETURN NEW;", hash='318f7ae0e71a0c48b85ab78816aa774fae4f0c44', operation='INSERT OR UPDATE OF "title", "subtitle", "series", "search_vector"', pgid='pgtrigger_update_search_vector_on_book_edit_2917c', table='reeltalk_book', when='BEFORE')),
        ),
    ]
