# Generated by Django 5.2.16 on 2026-08-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0244_rebrand_hashed_index_and_trigger_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='code_of_conduct',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='support_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='support_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_goal',
        ),
        migrations.DeleteModel(
            name='AnnualGoal',
        ),
    ]
