# Generated by Django 5.2.16 on 2026-08-26 23:27

import reeltalk.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0248_remove_connector_and_readwise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reading_status',
            field=reeltalk.models.fields.CharField(blank=True, choices=[('to-read', 'To-Read'), ('read', 'Read')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='reading_status',
            field=reeltalk.models.fields.CharField(blank=True, choices=[('to-read', 'To-Read'), ('read', 'Read')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reading_status',
            field=reeltalk.models.fields.CharField(blank=True, choices=[('to-read', 'To-Read'), ('read', 'Read')], max_length=255, null=True),
        ),
    ]
