# Generated by Django 5.2.16 on 2026-09-03 18:23

import django.contrib.postgres.fields
import reeltalk.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0252_strip_quotation_feed_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feed_status_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('review', 'Reviews'), ('comment', 'Comments'), ('everything', 'Everything else')], max_length=10), default=reeltalk.models.user.get_feed_filter_choices, size=8),
        ),
    ]
