# Generated by Django 5.2.16 on 2026-09-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeltalk', '0253_alter_user_feed_status_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_language',
        ),
    ]
